export const SHOW_MOBILE_NAVIGATION_MENU = 'SHOW_MOBILE_NAVIGATION_MENU'
export const HIDE_MOBILE_NAVIGATION_MENU = 'HIDE_MOBILE_NAVIGATION_MENU'

export const PRODUCT_LIST_VIEW = 'PRODUCT_LIST_VIEW'
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_CLEAR_ITEMS = 'CART_RESET'
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_CLEAN = 'PRODUCT_DETAILS_CLEAN'