export const SHOW_MOBILE_NAVIGATION_MENU = 'SHOW_MOBILE_NAVIGATION_MENU'
export const HIDE_MOBILE_NAVIGATION_MENU = 'HIDE_MOBILE_NAVIGATION_MENU'

export const PRODUCT_LIST_VIEW = 'PRODUCT_LIST_VIEW'
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'